// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJzeZISBn5AZUboEXKav-3HmdSdOiwCzs',
    appId: '1:680674141466:web:2461d6b433e76cde6038a3',
    messagingSenderId: '680674141466',
    projectId: 'crudfirebase-c1ee1',
    authDomain: 'crudfirebase-c1ee1.firebaseapp.com',
    storageBucket: 'crudfirebase-c1ee1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5e2Yw69ppbHMIOMrf4xEItr39jecKVF0',
    appId: '1:680674141466:android:6df175df02240d6b6038a3',
    messagingSenderId: '680674141466',
    projectId: 'crudfirebase-c1ee1',
    storageBucket: 'crudfirebase-c1ee1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvmIrFQlbmZwLkajiWw3rlzJxLcHrVI_A',
    appId: '1:680674141466:ios:70f261a88e9ed46a6038a3',
    messagingSenderId: '680674141466',
    projectId: 'crudfirebase-c1ee1',
    storageBucket: 'crudfirebase-c1ee1.appspot.com',
    iosBundleId: 'com.example.crud1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvmIrFQlbmZwLkajiWw3rlzJxLcHrVI_A',
    appId: '1:680674141466:ios:6d8847a9cc41436e6038a3',
    messagingSenderId: '680674141466',
    projectId: 'crudfirebase-c1ee1',
    storageBucket: 'crudfirebase-c1ee1.appspot.com',
    iosBundleId: 'com.example.crud1.RunnerTests',
  );
}
